### ISSUE TITLE
RE help

### ISSUE THREAD

**Issue by OhGodAPet** [patrickschur/amdvbflash#1]
You wanted to RE it... I've sorta written my own: https://twitter.com/Wolf9466/status/1240921593863450624

**Comment by andrealmeid** [comment]
Hey @OhGodAPet, could please point where we can find the source of your tool? Thanks.

**Comment by andrealmeid** [comment]
> I've not made it public yet. Could I ask as to why? I'd provide a binary.

As you know, our goal is to reverse engineer the tool and provide it as free software. Providing a binary would not help, as we it would need to reverse engineer it as well.

**Comment by OhGodAPet** [comment]
I can show you how it works.

**Comment by andrealmeid** [comment]
> I can show you how it works.

Talk is cheap. Show me the code.

**Comment by OhGodAPet** [comment]
> > I can show you how it works.
> 
> Talk is cheap. Show me the code.

Here - this isn't mine, though - missing register locations and definitions for Vega and Navi: https://github.com/libv/flashrom/blob/ati/ati_spi.c

**Comment by patrickschur** [comment]
@OhGodAPet In your twitter post you said you flashed a Navi10 card. Because there is no support for Vega and Navi cards in Flashrom, would you share your findings with us?

**Comment by OhGodAPet** [comment]
> @OhGodAPet In your twitter post you said you flashed a Navi10 card. Because there is no support for Vega and Navi cards in Flashrom, would you share your findings with us?

YES. This is what I wanted to express. I simply wrote really bad, hackish code and am sort of ashamed of it. HOWEVER...

**#define SMU11_MMIO_BAR			5

#define SMU11_GPIOPAD_MASK			0x5A4AC
#define SMU11_GPIOPAD_A				0x5A4B0
#define SMU11_GPIOPAD_EN			0x5A4B8

#define SMU11_ROM_CNTL				0x5A380		// 0x168e0
#define SMU11_PAGE_MIRROR_CNTL		0x5A384		// 0x168e1
#define SMU11_ROM_STATUS			0x5A388		// 0x168e2
#define SMU11_CGTT_ROM_CLK_CTRL0	0x5A38C		// 0x168e3
#define SMU11_ROM_INDEX				0x5A390		// 0x168e4
#define SMU11_ROM_DATA				0x5A394		// 0x168e5
#define SMU11_ROM_START				0x5A398		// 0x168e6
#define SMU11_ROM_SW_CNTL			0x5A39C		// 0x168e7
#define SMU11_ROM_SW_STATUS			0x5A3A0		// 0x168e8
#define SMU11_ROM_SW_COMMAND		0x5A3A4		// 0x168e9
#define SMU11_ROM_SW_DATA_0x00		0x5A3A8		// 0x168ea

#define SMU11_ROM_SW_DATA_0xFC		0x5A798
#define SMU11_ROM_SW_DATA(off)		(SMU11_ROM_SW_DATA_0x00 + (off))

#define SMU11_ROM_SW_STATUS_LOOP_COUNT 1000

#define SMU11_SPI_TRANSFER_SIZE 0x100**

I can offer more if needed, that's just part of my shitty macros >.>

**Comment by OhGodAPet** [comment]
I'm working with flashrom guys now to get it cleaned up and all.
