### ISSUE TITLE
Is there a source code?

### ISSUE THREAD

**Issue by shmerl** [patrickschur/amdvbflash#3]
The source doesn't really have any source in it.

**Comment by andrealmeid** [comment]
> The source doesn't really have any source in it.

Hello @shmerl, unfortunately we don't have the source code as well, we only have the binary. As stated in [README](https://github.com/patrickschur/amdvbflash#contributing), we would like to reverse engineer in the future and release as free software.

**Comment by justinclift** [comment]
@andrealmeid How far into the reversing process are people?

Asking because the "Wiki" entry here doesn't seem active yet.  Was kind of thinking that might hold info as to which tools and approaches are being tried (etc). :smile:

**Comment by andrealmeid** [comment]
@justinclift as far as I know, no one started this process yet, so that's why we don't have any info here. People from [flashrom](https://www.flashrom.org/Flashrom) probably could help us.

If you have the skills and energy to start that, go for it! :)

**Comment by justinclift** [comment]
> If you have the skills and energy to start that, go for it! :)

Was thinking it over, but I really shouldn't.  I'm already deeply involved in [some coding tasks](https://github.com/sqlitebrowser/dbhub.io) that are taking up tonnes of time, and if I let myself get too distracted that would suffer. :frowning:
