### ISSUE TITLE
Does not seem to pick up on Ryzen 7 2700u

### ISSUE THREAD

**Issue by scruffidog** [patrickschur/amdvbflash#4]
Including the output of a verbose lspci:
[lspci.txt](https://github.com/patrickschur/amdvbflash/files/4567063/lspci.txt)

and an strace of root executed amdvbflash -i:
[strace.txt](https://github.com/patrickschur/amdvbflash/files/4567064/strace.txt)

forgot to mention:
was also following the uefi version (via [techpowerup.com](https://www.techpowerup.com/download/ati-atiflash/)) which claimed that it added support for Vega a few versions back. But it also did not work. Not sure if this project is in lock step with the uefi version or not but just thought I'd bring it up.

**Comment by justinclift** [comment]
As a general thought, amdvbflash doesn't seem to handle integrated GPU's of any sort.  At least, not at this stage: https://github.com/patrickschur/amdvbflash/issues/2#issuecomment-622323257

**Comment by scruffidog** [comment]
Well, if there is any other info that can be provided, let me know. Much appreciation for this project even existing and moving forward!

**Comment by andrealmeid** [comment]
I can confirm that the tool also didn't worked with my integrated GPU, and all reports about this says the same, I didn't heard of a single success case.

Given all that, I believe that this isn't supported by the tool. I'll close this for now, but if you ever discovery something related to this, please add here. Thanks!
